name: Build and deploy
on:
  push:
  # schedule:
  #   - cron: "30 2 * * *"
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
        id: configure_pages
      - uses: paradicms/directory-etl-action@v1-beta
      - uses: paradicms/ssg-action@v1-beta
        env:
          NEXT_BASE_PATH: ${{ steps.configure_pages.outputs.base_path }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: ${{ github.ref == 'refs/heads/main' }}
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
